#!/usr/bin/env sh

if [ "$#" -ne 1 ] || ! expr "$1" : '^[0-9]\+$' >/dev/null; then
    echo "Usage: $0 N  # N must be a positive integer" >&2
    exit 1
fi

currentMonitor=$( hyprctl activeworkspace | grep -oP '(?<=monitorID: )\d+' )

N=$1
base=$(( (N - 1) * 3 ))
ws1=$(( base + 2 ))
ws3=$(( base + 3 ))
ws2=$(( base + 1 ))

hyprctl --batch "dispatch workspace $ws1; dispatch workspace $ws2; dispatch workspace $ws3; dispatch focusmonitor $currentMonitor"
